tasks: make robust to accept empty body
In the previous backporter, it assumes that
PR template was filled in pull request body,
but there was a case that it does not satisfy it in
practical use case (fix a typo).

It will fix the following error:

  NoMethodError: undefined method 'gsub' for nil (NoMethodError)
            body = pull_request["body"].gsub(/\*\*Which issue\(s\) this PR fixes\*\*: \r\n/,
                                       ^^^^^

Signed-off-by: Kentaro Hayashi <hayashi@clear-code.com>