test_in_tcp: Make sure to select unused port
In the previous code an used port was stored in TcpInputTest::PORT, but
it doesn't make sure to be unused at run time of each tests. I think this
is the why sometimes tests for in_tcp fail on CI environment like this:

https://cloud.drone.io/fluent/fluentd/1449/1/2

  Error: test: source_address_key(TcpInputTest): Errno::EADDRINUSE: Address already in use - bind(2) for 0.0.0.0:45259
  /usr/local/lib/ruby/2.6.0/socket.rb:201:in `bind'
  /usr/local/lib/ruby/2.6.0/socket.rb:201:in `listen'
  /drone/src/vendor/bundle/ruby/2.6.0/gems/serverengine-2.2.4/lib/serverengine/socket_manager_unix.rb:66:in `listen_tcp_new'
  /drone/src/vendor/bundle/ruby/2.6.0/gems/serverengine-2.2.4/lib/serverengine/socket_manager.rb:124:in `block in listen'
  /drone/src/vendor/bundle/ruby/2.6.0/gems/serverengine-2.2.4/lib/serverengine/socket_manager.rb:122:in `synchronize'
  /drone/src/vendor/bundle/ruby/2.6.0/gems/serverengine-2.2.4/lib/serverengine/socket_manager.rb:122:in `listen'
  /drone/src/vendor/bundle/ruby/2.6.0/gems/serverengine-2.2.4/lib/serverengine/socket_manager.rb:131:in `listen_tcp'
  /drone/src/vendor/bundle/ruby/2.6.0/gems/serverengine-2.2.4/lib/serverengine/socket_manager_unix.rb:117:in `send_socket'
  /drone/src/vendor/bundle/ruby/2.6.0/gems/serverengine-2.2.4/lib/serverengine/socket_manager.rb:158:in `process_peer'
  ===============================================================================

This commit tries to fix it by selecting an unused port before running
each tests.

Signed-off-by: Takuro Ashie <ashie@clear-code.com>