console_adapter: support console gem v1.30 (#4857)
**Which issue(s) this PR fixes**: 
Fixes #

**What this PR does / why we need it**: 
This patch will fix following error:
```
NoMethodError: undefined method `seek' for nil:NilClass
/home/runner/work/fluentd/fluentd/lib/fluent/log/console_adapter.rb:61:in `call'
/opt/hostedtoolcache/Ruby/3.2.7/x64/lib/ruby/gems/3.2.0/gems/console-1.30.0/lib/console/output/wrapper.rb:35:in `call'
/opt/hostedtoolcache/Ruby/3.2.7/x64/lib/ruby/gems/3.2.0/gems/console-1.30.0/lib/console/output/failure.rb:38:in `call'
/opt/hostedtoolcache/Ruby/3.2.7/x64/lib/ruby/gems/3.2.0/gems/console-1.30.0/lib/console/filter.rb:48:in `block (3 levels) in []'
/home/runner/work/fluentd/fluentd/test/log/test_console_adapter.rb:58:in `test_args'
```

Ref. https://github.com/fluent/fluentd/actions/runs/13714056838

The variable name was changed at

https://github.com/socketry/console/commit/1529fefb4c7ff1742a54de6ca91eace3226a2947#diff-757206aeb67c0bd1c0d1813dfbff0a140a68920505520e8163b3a274fbab05ceR30

Since now Fluentd assumes Ruby 3.2 or later, this discards the related
code to support Ruby before v3.1.

**Docs Changes**:
Not needed.

**Release Note**: 
The same as the title.

Signed-off-by: Shizuo Fujita <fujita@clear-code.com>