Raise minimum required ruby version
The service discovery plugin helper use Array#prepend, it means that
the ruby version must be 2.5 or later precisely.

   fluentd.work/lib/fluent/plugin_helper/service_discovery.rb:71:in
   `service_discovery_configure': undefined method `prepend' for
   []:Array (NoMethodError) from
   /work/fluent/fluentd/fluentd.work/lib/fluent/plugin/out_

NOTE: It works with Ruby 2.5 or later, but 2.x had already
reached EOL. At least, it may better to set verified version with CI.

Signed-off-by: Kentaro Hayashi <hayashi@clear-code.com>