Include missing Fluent::Test::Helpers for assert_equal_event_time
InputTestDriver uses assert_equal_event_time, but this helper method
is used without proper "require". Without this fix, It causes the
following NoMethodError.

  NoMethodError: undefined method `assert_equal_event_time' for #<Fluent::Test::InputTestDriver:0x0055c638efd590>
  Did you mean?  assert_equal
/home/kenhys/.rvm/gems/ruby-2.4.1@fluentd-latest/gems/fluentd-0.14.14/lib/fluent/test/input_test.rb:155:in `block (2 levels) in run'
/home/kenhys/.rvm/gems/ruby-2.4.1@fluentd-latest/gems/fluentd-0.14.14/lib/fluent/test/input_test.rb:152:in `each'
/home/kenhys/.rvm/gems/ruby-2.4.1@fluentd-latest/gems/fluentd-0.14.14/lib/fluent/test/input_test.rb:152:in `block in run'
/home/kenhys/.rvm/gems/ruby-2.4.1@fluentd-latest/gems/fluentd-0.14.14/lib/fluent/test/base.rb:71:in `run'
/home/kenhys/.rvm/gems/ruby-2.4.1@fluentd-latest/gems/fluentd-0.14.14/lib/fluent/test/input_test.rb:123:in `run'