command: binlog_reader: Add a missing fluent/env require
Otherwise, the following error occurred:

```log
`<module:Mixin>': undefined method `windows?' for Fluent:Module (NoMethodError)
```

Signed-off-by: Hiroshi Hatake <hatake@calyptia.com>