Fix missing runtime bundler dependency
It fixes the following error with fluentd --gemfile Gemfile
when bundler is not installed.

  error: Gem::MissingSpecError

Closes: #1481

NOTE: since ruby 2.6 or later, bundler is bundled with ruby itself,
so this error is occurred with ruby 2.5 which will reache EOL
at 2021-03-31.

Signed-off-by: Kentaro Hayashi <hayashi@clear-code.com>