Win32Error: Add to_s and inspect methods and remove message
Since the previous code doesn't have to_s method, it shows only
`Fluent::Win32Error`, doesn't show the detail.

Signed-off-by: Takuro Ashie <ashie@clear-code.com>